@startuml

!theme plain
autonumber 1.1

skinparam SequenceBoxBorderColor #bbbbbb

box "Normal world"
participant "Normal\nSSP driver" as nsd
participant "Normal controller" as normcont
end box
box "Secure world"
participant "Secure controller" as seccont
participant "Secure\nSSP driver" as ssd
end box

ssd -> ssd ++: Boot
    ssd -> seccont ++: ssp_register(uuid)
        seccont -> normcont ++: Save uuid
            return
        return

autonumber inc A
nsd -> nsd ++: Load
    nsd -> normcont ++: nsp_register(uuid, notif_handler)
        return

autonumber inc A
ssd <- ++: Interrupt
    ssd -> seccont ++: ssp_notify(uuid)
        seccont -> normcont ++: Interrupt
            seccont --> ssd --: Handled
        ssd --> ssd --: Handled

...

normcont -> nsd ++: notif_handler()
    nsd -> ssd ++: TEEC_InvokeCommand(commandID)
        return
    return
normcont --> normcont --: Handled

@enduml