@startuml

!theme plain
' autonumber 1.1

skinparam SequenceBoxBorderColor #bbbbbb

box "Normal world"
participant "Normal world\nSSP driver" as nsd
participant "Normal world\nSSP controller" as normcont
end box
box "Secure world"
participant "Secure world\nSSP Controller" as seccont
participant "Secure world\nSSP driver" as ssd
end box

nsd -> nsd ++: Load
    nsd -> normcont ++: norm_ssp_register(sec_uuid, notif_handler)
        return

ssd <- ++: Interrupt
    ssd -> seccont ++: sec_ssp_notify(sec_uuid)
        seccont --> normcont ++: Interrupt
            seccont --> ssd --: Handled
        ssd --> ssd --: Handled

...

normcont -> nsd ++: notif_handler()
    nsd -> ssd ++: TEEC_InvokeCommand(commandID)
        return
    return
normcont --> normcont --: Handled

@enduml