# Building & running OP-TEE

## QEMU

### Download of repositories

OP-TEE uses a [central repository](https://github.com/Distrinet-TACOS/manifest.git) containing the manifest files for repo for all architectures. To download all necessary git repositories of the OP-TEE project for the QEMUv7 architecture, execute the following commands:

``` bash
mkdir -p <project-dir>
cd <project-dir>
repo init -u https://github.com/Distrinet-TACOS/manifest.git -m tacos-qemu.xml
repo sync -j4 --no-clone-bundle
```

### Toolchains

The toolchains required to build any part of OP-TEE are included in one of the repositories downloaded in the previous step. To download the actual toolchains, execute

``` bash
cd <project-dir>/build
make -j2 toolchains
```

### Build OP-TEE

The OP-TEE project has three main parts: the operating system, the client API and the trusted applications. These three parts can be built on their own, but to get started it is easier to build the whole system at once. This is as simple as executing

``` bash
cd <project-dir>/build
make -j `nproc`
```

This process will take some time.

### Running OP-TEE

QEMU and OP-TEE can be launched by executing

``` bash
cd <project-dir>/build
make run -j `nproc`

# After the command prompt (qemu) appears, press c to start execution.
c
```

This will launch QEMU in the current terminal and two new terminals, one serial connection to the secure world and one to the normal world. In the normal world terminal, you can login using the users `root`or `test`, after which it is possible to run programs in the normal world that interact with the secure world.

To test if everything went according to plan, run `xtest` once logged in. If there are no obvious errors, the build process should have completed successfully. You can run the example programs by executing any of the `optee_example_*` programs present in the path.

The command ``make run-only -j `nproc` `` is also available to run QEMU without building the project.

## Sabre Lite

### Download of repositories

The i.MX6 build system is based on a customized Buildroot. The TACOS related changes are maintained in [our fork of Buildroot](https://github.com/Distrinet-TACOS/buildroot.git). To initialize the build environment, create a project directory and clone the buildroot into this directory.

``` bash
mkdir -p <project-dir>
cd <project-dir>
git clone https://github.com/Distrinet-TACOS/buildroot.git
```

i.MX6 specific layer on buildroot called buildroot-external-boundary is provided by boundary devices. TACOS related modifications on this repo are maintained in a forked repository at [buildroot-external-boundary repository](https://github.com/Distrinet-TACOS/buildroot-external-boundary.git). Check out this repository in the same project folder as mentioned above.

``` bash
cd <project-dir>
git clone https://github.com/Distrinet-TACOS/buildroot-external-boundary.git
```

### Output folder for buildroot

Use the following command to overlay the i.MX6 related configurations, the Board Support Package (BSP), OPTEE configurations and TACOS related configurations on the Buildroot setup. The following command will create a directory named output and place the configurations in this folder.

``` bash
cd <project-dir>
make BR2_EXTERNAL=$PWD/buildroot-external-boundary/ -C buildroot/ O=$PWD/output nitrogen6x_optee_defconfig
```

### Build OP-TEE, Linux and the i.MX6 BSP

The simplest way to bootstrap is to issue a make command. This will fetch all the components and build Linux, OPTEE and OPTEE applications. The Linux image is bounded to the OPTEE image and an SD card image is created. 
 
``` bash
cd <project-dir>/output
make -j `nproc`
```

This process will take some time.

### Creating a bootable SD Card

The previous process will create an SD card image in the directory `<project-dir>/output/images/sdcard.img`. You can use an SD card flash tool such as [balenaEtcher](https://www.balena.io/etcher/) to flash the image on an SD Card.

### Connecting the BD-SL-i.MX6 Serial

The BD-SL-i.MX6 board has two UART connections. The UART connection labled 'Console' will be connected to OPTEE while the other UART will be connected to the Linux running in the Normal world. Once the UART cables are connected and their interfaces are attached to separate console windows. Power up the BD-SL-i.MX6 board and you will see boot logs for OPTEE on the UART labeled console and the Linux logs on the other UART. You can now log in to linux and look around or start an example client application available onboard.

It might be that only one serial connection is used to output both the normal and the secure world consoles. To change this, during the first moments of the boot process, press any key to stop the autoboot. Enter the following in the terminal that appears.

``` txt
setenv console ttymxc0
saveenv
reboot
```

The device should now use both serial connections.
