name: Render & deploy quarto webpage to Pages

on:
  workflow_dispatch:
  push:
    branches: main

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  QUARTO_VERSION: 1.2.335

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  render:
    name: Render
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v3
      - name: Download and install Quarto
        run: |
          wget "https://github.com/quarto-dev/quarto-cli/releases/download/v$QUARTO_VERSION/quarto-${QUARTO_VERSION}-linux-amd64.deb"
          dpkg -i quarto-$QUARTO_VERSION-linux-amd64.deb
          quarto check install
      - name: Render
        run: quarto render
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: render
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1